//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cash.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fund
    {
        public int ID { get; set; }
        public decimal Amount { get; set; }
        public int AccountID { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
