//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cash.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Loan()
        {
            this.Installments = new HashSet<Installment>();
        }
    
        public int ID { get; set; }
        public decimal Amount { get; set; }
        public decimal InstallmentAmount { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> AccountID { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public Nullable<decimal> CashRemainingAmount { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Installment> Installments { get; set; }
    }
}
